### ISSUE TITLE
Publishing plugin on SonarQube marketplace

### ISSUE THREAD

**Issue by cadnan** [Embarcadero/SonarDelphi#13]
Are there any plans on publishing this plugin on SonarQube marketplace?
Info here: [Deploying to the Marketplace](https://community.sonarsource.com/t/deploying-to-the-marketplace/35236)

My organization has a SonarQube server and they only install plugins that are listed in the plugin version compatibility matrix, like for example [here](https://docs.sonarsource.com/sonarqube/9.9/instance-administration/plugin-version-matrix)

**Comment by Cirras** [comment]
Hi @cadnan,

The IntegraDev SonarDelphi plugin has requested inclusion in the SonarQube Marketplace.
See: https://community.sonarsource.com/t/new-plugin-sonardelphi-requesting-inclusion-in-sonarqube-marketplace/104547

**Comment by Cirras** [comment]
The IntegraDev SonarDelphi plugin is now available on the SonarQube Marketplace. 😃

![image](https://github.com/Embarcadero/SonarDelphi/assets/22178573/0ed3a9b4-8ecd-46ed-a9c5-1075034d94b5)

**Comment by cadnan** [comment]
That was fast! Thanks a lot @Cirras for your effort on making this happen.
