### ISSUE TITLE
Add more exceptions to the EmptyBlock rule

### ISSUE THREAD

**Issue by Indigo744** [Embarcadero/SonarDelphi#18]
The EmptyBlock rule is currently defined as is:
> **Either remove or fill this block of code.**
> Most of the time a block of code is empty when a piece of code is really missing. An empty block should be either filled or removed.
> **Exceptions**
> Empty routine bodies (covered by the EmptyRoutine rule)
> Empty except blocks (covered by the SwallowedException rule)
> Case blocks that are empty apart from a comment

I think the last exception can be made broader: **_any_ blocks that are empty apart from a comment**.

Example that triggers a finding related to this rule, but should not:
```
if condition then
begin
    // Comment explaining why this branch is empty
end;
```

This is the way other scanner are implementing this rule. And it makes sense! Comments _are_ part of the code (and act as documentation).

For reference: https://sonarsource.github.io/rspec/#/rspec/S108/csharp
> Exception : The rule ignores code blocks that contain comments.

**Comment by fourls** [comment]
Hi @Indigo744, this SonarDelphi fork is no longer maintained and does not contain an EmptyBlock rule.

From the rule description (which I wrote!) it looks like you're using the actively maintained [integrated-application-development/sonar-delphi](https://github.com/integrated-application-development/sonar-delphi) (the version on the Sonar Marketplace). If you re-raise your issue on that repository, we can discuss this improvement there.

**Comment by Indigo744** [comment]
@fourls Indeed you're right! Sorry, I'll recreate there.
